# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
podspec :path => "../UIImageView+SDWebImage_M13ProgressSuite.podspec"

target "Demo" do
  pod "UIImageView+SDWebImage_M13ProgressSuite", :path => "../"
end

# Uncomment the following lines to add testing dependencies
# target "DemoTests" do
#   pod 'Expecta'
# end

